baseURL = 'https://hung-nguyen-quoc11278.github.io/hungdaily-blog/'
languageCode = 'vi'
title = 'Hung Daily Blog'
theme = 'blowfish'

[params]
  homepageStyle = "card"
  displayFullLogo = false
  showRecent = true
  recentLimit = 5
  enableSearch = true
  showRecentArticles = true
  articleView = "card"
  showTaxonomies = true
  showAuthor = true

[author]
  name = "Hung Nguyen"
  image = "img/author.jpg"
  headline = "Lười thâm niên"
  bio = "Lười, cụ thể là boss lười"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/Hung-Nguyen-Quoc11278"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[outputs]
  home = ["HTML", "JSON", "RSS"]

[[menu.main]]
  name = "Bài viết"
  pageRef = "/posts"
  weight = 1

[[menu.main]]
  name = "Chủ đề"
  pageRef = "/categories"
  weight = 2

[[menu.main]]
  name = "Thẻ"
  pageRef = "/tags"
  weight = 3